### ISSUE TITLE
[Bug]: Spoiler arming keybind requires SHIFT, ALT or CTRL

### ISSUE THREAD

**Issue by Guy-Adler** [GeoFS-Extensions/autoland#127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When not using SHIFT, ALT or CTRL in a keybind set by keyboard mapping, spoilers arming does not work.

### Expected behavior

Spoilers arming should work even with a keycode only keybind.

### Actual behavior

Spoilers arming only works when using a keybind including SHIFT, ALT or CTRL.

### Operating System

Windows 10 21H1

### Browser

Chrome 95.0.4638.54
Edge 95.0.1020.40

### Version

3.3.0

**Comment by Guy-Adler** [comment]
This is caused by spoilers_arming/source/chabgeControls.ts:53-61.
We should compare the event code to `Airbrake toggle (on/off)` instead of `Spoilers Arming`.
While doing so, we might as well compare the rest of the meta keys to the keybind, to make it so changing the spoilers toggle key doesn't break stuff.

**Comment by nicolas377** [comment]
Is this behavior observed with or without keyboard mapping, or in both scenarios?
