### ISSUE TITLE
[feat]: draw fmc route on map

### ISSUE THREAD

**Issue by nicolas377** [GeoFS-Extensions/autoland#133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Historically, fmc was able to draw out the route that it would follow on the GeoFS map. After GeoFS switched away from Google Maps, the creators of fmc had to remove support for that feature. Now, GeoFS uses a library, leaflet.js, that exposes an API for us to modify the map. Using their API, we can re-add that feature.

This should be a tracking issue for that feature. As of now, we plan to have this feature be in public experimental mode at 3.4.0, and be patched and ready for full release in 3.5.0.

**Comment by nicolas377** [comment]
@Guy-Adler could you make a prototype of some lines and points on the geo map? If you can, make that prototype a branch on this repo. You don't need to maintain it, we can port the prototype to main when we're ready to.

**Comment by Guy-Adler** [comment]
I'l be able to get some work done on it over the weekend
