### ISSUE TITLE
[bug]: script injection is unreliable

### ISSUE THREAD

**Issue by nicolas377** [GeoFS-Extensions/autoland#145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Recently, there have been a flurry of reports about scripts not injecting reliably. I haven't done a binary search to find the breaking commit yet, but my suspicion is that this popped up in 723fd82bf353c5d66a5c6da9a029d299562c7e4e

### Expected behavior

Scripts to inject the first time GeoFS is loaded.

### Actual behavior

Scripts take multiple reloads to inject, and sometimes don't all inject.

### Operating System

Windows 10 (no version number as of yet)

### Browser

Chrome (no version number as of yet)

### Version

3.3.1

**Comment by Guy-Adler** [comment]
I'll try to get some work on it during the weekend,
