### ISSUE TITLE
[feat]: condense options into one entry

### ISSUE THREAD

**Issue by nicolas377** [GeoFS-Extensions/autoland#36]
Right now, we're storing 3 things:
- `update`, which can be defined by this interface:
```ts
interface update {
  shouldBeUpdated: boolean,
  /** the version number we should be updating to */
  new?: string,
}
```
- `devModeEnabled`, which is just a single boolean.
- `options`, which is defined [here](https://github.com/GeoFS-Extensions/autoland/blob/42be940235c07269635b66229b95b3fb829a0d63/extension/source/background.ts#L3)
    - We need to add keyboardmapping [here](https://github.com/GeoFS-Extensions/autoland/blob/42be940235c07269635b66229b95b3fb829a0d63/extension/source/background.ts#L251)

We can condense this all down into one entry. We can define its shape with a .d.ts file in the types folder that exports an interface that we can use (and maybe also the scripts type that contains the names of the scripts.

**Comment by nicolas377** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Rename prefs to script prefs](https://trello.com/c/rRSp9tpk/65-rename-prefs-to-script-prefs)

**Comment by nicolas377** [comment]
We should probably just overhaul the options system to be stored under one chrome.storage entry. @Guy-Adler what do you think about that?

**Comment by Guy-Adler** [comment]
Makes sense
So like one JSON object?

**Comment by nicolas377** [comment]
Yeah. It'll also be easier to make (and update) one coherent TS interface across all the files.

**Comment by nicolas377** [comment]
I'm not sure whether this should be a patch or a minor version update. Since this would be a incompatible API change, [semver](https://semver.org/) says we should increment the major version, but we haven't used anything like that for previous incompatible API changes. Your opinions @GeoFS-Extensions/authors?

**Comment by Guy-Adler** [comment]
I'd say we should use the major version number for a complete change of the infrastructure (like going to a chrome extension or from manifest v2 to v3). Since it will not be noticed by most users but will affect the code, I'd say we should increment the minor version number.

**Comment by nicolas377** [comment]
That could be part of 3.3.0. Your thoughts?

**Comment by Guy-Adler** [comment]
I think it's a good idea

**Comment by nicolas377** [comment]
A lot of stuff in the infra could use some redoing, so we're going to refactor all the extension infrastructure. That's way outside the scope of this issue though, so I'm closing this issue in favor of another issue to track that.
