### ISSUE TITLE
[feat]: Add support for transparent UI

### ISSUE THREAD

**Issue by nicolas377** [GeoFS-Extensions/autoland#64]
This is a tracking issue for adding support for transparent AP++ and FMC UI's.

Todo list:
- [ ] Settle on a prototype to match.
- [ ] Add transparent UI in AP++.
- [ ] Add transparent UI in FMC.
- [ ] Test together.

**Comment by Guy-Adler** [comment]
Making the ap++ controls transparent makes them pretty much invisible, because of the shape of the transparent UI (`radial-gradient(farthest-corner at 0 0, #ffffffe0 40%, #ffffff00 70%)`).
Example:
![image](https://user-images.githubusercontent.com/44903310/134824963-05537d02-842c-45bf-8168-4c61fa1f964f.png)
I'm open to other ideas.

**Comment by nicolas377** [comment]
AP++ transparency is definitely something that needs designing then. For now, we can just make the FMC icons transparent like the rest of the bottom bar. @Guy-Adler could you get a prototype image for that?

**Comment by Guy-Adler** [comment]
Something like this?
![image](https://user-images.githubusercontent.com/44903310/134909185-b781d623-ea4e-43a3-b628-82b9be3fe7cc.png)

**Comment by nicolas377** [comment]
Maybe more green in it, but what was the style you used for that prototype image?

**Comment by Guy-Adler** [comment]
I just removed the styling of the button in the dev tools (background color and color)

**Comment by nicolas377** [comment]
Alright. I'll work on another prototype image when I get home.

**Comment by nicolas377** [comment]
For the ap++ controls, we could have them adhere to the normal gradient geo uses, and when the user hovers over the controls, fade it to the regular one. I'll look at either fading just the ap++ controls or the whole nav tab. I think fading the whole nav tab would look more pleasant, and I'll throw up a few prototype gifs when I get them.

**Comment by nicolas377** [comment]
I completely forgot about this for a while, since I've working on the monorepo integration. I'll try and get some prototypes up Friday afternoon my time.

**Comment by nicolas377** [comment]
Here's the prototype I'm thinking of right now for ap++:
When the mouse is over something else, ap++ will conform to the [map's style](https://user-images.githubusercontent.com/44903310/134824963-05537d02-842c-45bf-8168-4c61fa1f964f.png). When the mouse is over the ap++ holder div (raw html says there's 2 divs, we can wrap them if needed), the controls can fade into full view, with rounded transparency on the corners.
I won't be able to get a prototype up until this weekend, but when I do, it'll be on a branch that we can leave alone until we're ready to bring the html and css additions into main. I'll publish that branch and put a gif up here.

**Comment by nicolas377** [comment]
For FMC, we can just make everything transparent. We should keep a little green when we have it, but we won't need any fading like AP++ would.
